-- ============================================================================
-- SEED CONTENT: exams, quotes, study vibes, ambient tracks
-- ============================================================================

insert into public.exams (name, short_name, session, authority, exam_date, status, expected_date, official_url, description, display_order, is_active, category, target_score, syllabus_tips, is_target, expected_note) values
('JEE Main 2027', 'JEE Main', 'Session 1', 'National Testing Agency (NTA)', null, 'expected', '2027-01-20T00:00:00+00:00', 'https://jeemain.nta.nic.in/', 'Joint Entrance Examination (Main) — Session 1 for engineering admissions.', 1, true, 'JEE', '220+ / 300 (99.5+%ile)', ARRAY['Master Class 11 Physics mechanics & organic chemistry early','Daily 30 PYQs with speed-accuracy tracking'], true, null),
('JEE Main 2027', 'JEE Main', 'Session 2', 'National Testing Agency (NTA)', null, 'expected', '2027-04-02T00:00:00+00:00', 'https://jeemain.nta.nic.in/', 'Joint Entrance Examination (Main) — Session 2 for engineering admissions.', 2, true, 'JEE', '220+ / 300 (99.5+%ile)', ARRAY['Master Class 11 Physics mechanics & organic chemistry early','Daily 30 PYQs with speed-accuracy tracking'], false, null),
('JEE Advanced 2027', 'JEE Advanced', null, 'IIT (host institute, TBD)', null, 'not_announced', '2027-05-08T12:40:21.69845+00:00', 'https://jeeadv.ac.in/', 'Joint Entrance Examination (Advanced) for IIT admissions.', 3, true, 'JEE', 'Under 1000 All India Rank', ARRAY['Focus on multi-concept numerical problems','Analyze previous 10 years IIT JEE paper patterns'], false, 'Date not yet announced by the conducting authority — showing a provisional placeholder.'),
('NEET UG 2027', 'NEET UG', null, 'National Testing Agency (NTA)', null, 'expected', '2027-05-02T00:00:00+00:00', 'https://neet.nta.nic.in/', 'National Eligibility cum Entrance Test for undergraduate medical admissions.', 4, true, 'NEET', '680+ / 720 (AIIMS Goal)', ARRAY['NCERT line-by-line mastery for Biology','Solve 100 Physics MCQs daily with error log'], false, null),
('NDA & NA II 2026', 'NDA II', null, 'Union Public Service Commission (UPSC)', '2026-09-13T00:00:00+00:00', 'official', '2026-09-13T00:00:00+00:00', 'https://upsc.gov.in/', 'National Defence Academy & Naval Academy Examination (II), 2026. Admin must set the official UPSC date.', 5, true, 'NDA', '450+ / 900 Written Score', ARRAY['Daily Mathematics speed practice (120 questions)','Current affairs & General English revision'], false, null),
('CUET UG 2027', 'CUET UG', null, 'National Testing Agency (NTA)', null, 'not_announced', '2027-05-08T12:40:21.69845+00:00', 'https://cuet.nta.nic.in/', 'Common University Entrance Test for undergraduate admissions.', 6, true, 'CUET', '800/800 Percentile Score', ARRAY['NCERT domain subject thorough revision','Speed practice for General Test & Language modules'], false, 'Date not yet announced by the conducting authority — showing a provisional placeholder.');
insert into public.quotes (text, author, category, is_active, is_featured) values
('Discipline beats motivation.', 'PeaceGhost Study System', 'discipline', true, false),
('Your future result is being built today.', 'PeaceGhost Study System', 'consistency', true, false),
('One focused hour today can change your tomorrow.', 'PeaceGhost Study System', 'focus', true, false),
('Don''t chase motivation. Build momentum.', 'PeaceGhost Study System', 'discipline', true, false),
('You don''t need a perfect day. You need a productive one.', 'PeaceGhost Study System', 'consistency', true, false),
('Small daily improvements compound into remarkable results.', 'PeaceGhost Study System', 'consistency', true, false),
('The pain of discipline weighs ounces. The pain of regret weighs tons.', 'PeaceGhost Study System', 'discipline', true, false),
('You don''t rise to the level of your goals. You fall to the level of your systems.', 'PeaceGhost Study System', 'discipline', true, false),
('Consistency is what transforms average into excellence.', 'PeaceGhost Study System', 'consistency', true, false),
('Focus on the process. The result takes care of itself.', 'PeaceGhost Study System', 'focus', true, false),
('You are not behind. You are exactly where your effort has placed you — now move.', 'PeaceGhost Study System', 'comeback', true, false),
('It''s never too late to start again.', 'PeaceGhost Study System', 'comeback', true, false),
('One bad week doesn''t define your preparation. Quitting does.', 'PeaceGhost Study System', 'comeback', true, false),
('Discipline is the bridge between goals and accomplishment.', 'PeaceGhost Study System', 'discipline', true, false),
('Your only competition is who you were yesterday.', 'PeaceGhost Study System', 'general', true, false),
('Hard choices, easy life. Easy choices, hard life.', 'PeaceGhost Study System', 'general', true, false),
('Nobody is coming to save you. Save yourself, one study session at a time.', 'PeaceGhost Study System', 'discipline', true, false),
('Motivation gets you started. Habit keeps you going.', 'PeaceGhost Study System', 'consistency', true, false),
('You don''t need more time. You need more focus in the time you have.', 'PeaceGhost Study System', 'focus', true, false),
('Distraction is the tax you pay for not having clarity of purpose.', 'PeaceGhost Study System', 'focus', true, false),
('Every topic you avoid becomes the question you fear.', 'PeaceGhost Study System', 'focus', true, false),
('The version of you who cracks this exam is built in ordinary, unremarkable study sessions.', 'PeaceGhost Study System', 'consistency', true, false),
('Comparison steals focus. Redirect it into your next chapter.', 'PeaceGhost Study System', 'focus', true, false),
('Discomfort today is currency for freedom tomorrow.', 'PeaceGhost Study System', 'discipline', true, false),
('Stop waiting for the right mood. Start and the mood follows.', 'PeaceGhost Study System', 'discipline', true, false),
('The syllabus doesn''t shrink by worrying about it. It shrinks by studying it.', 'PeaceGhost Study System', 'focus', true, false),
('You are one focused week away from feeling in control again.', 'PeaceGhost Study System', 'comeback', true, false),
('Aspirants who win are not the ones with no doubts — they''re the ones who study anyway.', 'PeaceGhost Study System', 'discipline', true, false),
('You don''t need to feel ready. You need to start.', 'PeaceGhost Study System', 'general', true, false),
('Progress hides inside boring, repeated effort.', 'PeaceGhost Study System', 'consistency', true, false),
('The best time to fix a weak chapter was last month. The next best time is today.', 'PeaceGhost Study System', 'focus', true, false),
('Success is a few disciplined decisions, repeated daily, compounded over months.', 'PeaceGhost Study System', 'discipline', true, false),
('Every focused session is a deposit into a future you''re proud of.', 'PeaceGhost Study System', 'consistency', true, false),
('JEE doesn''t reward talent. It rewards consistency.', 'PeaceGhost Study System', 'JEE', true, false),
('Every JEE topper was once confused by the same concepts you are.', 'PeaceGhost Study System', 'JEE', true, false),
('NCERT first. Depth later.', 'PeaceGhost Study System', 'NEET', true, false),
('NEET is a marathon of retention, not a sprint of intelligence.', 'PeaceGhost Study System', 'NEET', true, false),
('Every biology diagram you skip today is a mark you lose tomorrow.', 'PeaceGhost Study System', 'NEET', true, false),
('NDA rewards discipline before it rewards academics — build both.', 'PeaceGhost Study System', 'NDA', true, false),
('Physical fitness and mental sharpness are trained the same way: daily reps.', 'PeaceGhost Study System', 'NDA', true, false),
('Service before self starts with discipline before comfort.', 'PeaceGhost Study System', 'NDA', true, false),
('CUET tests your consistency across subjects, not your genius in one.', 'PeaceGhost Study System', 'CUET', true, false),
('Balance your CUET prep the way toppers balance their subjects: evenly, daily.', 'PeaceGhost Study System', 'CUET', true, false),
('A good CUET score is built months before the admit card, not the week before.', 'PeaceGhost Study System', 'CUET', true, false),
('The competition is studying right now.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('Every rank list has a name. It could be yours.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('The exam doesn''t care how you feel. Show up anyway.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('Revision is where marks are actually won.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('PYQs are the closest thing to a conversation with the exam itself.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('Mocks don''t measure your intelligence. They measure your exam temperament.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('Your rank is a receipt. Your preparation is the purchase.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('The exam is a deadline. Preparation is a lifestyle.', 'PeaceGhost Study System', 'exam_pressure', true, false),
('Study like the aspirant who is 5 marks ahead of you is studying right now.', 'PeaceGhost Study System', 'exam_pressure', true, false);

insert into public.study_vibes (title, category, image_url, mobile_image_url, overlay_strength, is_active, display_order, photographer, source_name, source_url, license, quote_text) values
('Rainy Night Study Sanctuary','rain','https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',0.55,true,1,'Benjamin Davies','Unsplash','https://unsplash.com','Unsplash Free License','While the rain falls outside, your mind builds tomorrow.'),
('2 AM Midnight Desk & Coffee','night','https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80',0.6,true,2,'Andrew Neel','Unsplash','https://unsplash.com','Unsplash Free License','The quietest hours reveal the strongest determination.'),
('Grand Academic Library','library','https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=80',0.5,true,3,'Giammarco Boscaro','Unsplash','https://unsplash.com','Unsplash Free License','Surrounded by centuries of knowledge, standing on the shoulders of giants.'),
('Science & Equations Laboratory','science','https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=900&q=80',0.5,true,4,'Hans-Peter Gauster','Unsplash','https://unsplash.com','Unsplash Free License','Every law of physics was once a mystery someone refused to leave unsolved.'),
('Handwritten Mathematics & Calculus','math','https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=900&q=80',0.55,true,5,'Antoine Dautry','Unsplash','https://unsplash.com','Unsplash Free License','Mathematics is not about numbers, equations, or algorithms: it is about understanding.'),
('Sunrise Focus Desk','morning','https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80',0.45,true,6,'STIL','Unsplash','https://unsplash.com','Unsplash Free License','Before the world wakes up and gets loud, conquer your first victory.'),
('Exam Mode Concentration','exam','https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=2000&q=80','https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=80',0.5,true,7,'Green Chameleon','Unsplash','https://unsplash.com','Unsplash Free License','The exam won''t measure your wishes. It will measure your preparation.');

insert into public.ambient_tracks (title, category, duration, is_active, display_order, volume_recommendation) values
('Soft Window Rain','rain','Infinite Loop',true,1,0.6),
('Deep Focus Alpha Waves (528Hz)','deep_focus','Infinite Loop',true,2,0.5),
('Quiet Library Atmosphere','library','Infinite Loop',true,3,0.4),
('Subtle Study Café','cafe','Infinite Loop',true,4,0.4),
('Calm Ocean Shore','ocean','Infinite Loop',true,5,0.5),
('Pine Forest Wind','forest','Infinite Loop',true,6,0.4),
('Pink Focus Noise','white_noise','Infinite Loop',true,7,0.3),
('Complete Silence','silent','Off',true,8,0);
